
selectMode = "Seleccionar modo"
fourAxisSimple = "4 ejes simple"
fourS = "4S"
accept = "Aceptar"

openModel = "Abrir modelo"
saveModel = "Guardar modelo"

openGcode = "Abrir gcode"
saveGcode = "Guardar gcode"
deform = "Desformar"
deformationFactor = "Factor de desformación"
deformer = "Desformador"
undeformer = "Reformador"

zerothOrderSlider = "Orden cero"
firstOrderSlider = "Primer orden"
secondOrderSlider = "Segundo orden"
temperatureSlider = "Temperatura de extrusion"
startSlider = "Radio inicial (expermiental)"
endSlider = "Radio final (expermiental)"
xTranslation = "Desplazamiento X"
yTranslation = "Desplazamiento Y"
zTranslation = "Desplazamiento Z"
neighbourLossWeight = "Peso de los vecinos en la optimización"
maxOverhang = "Voladizo máximo"
rotationMultiplier = "Multiplicador de rotación"
initialRotationToZero = "Rotación inicial en cero"
initialRotationFieldSmoothing = "Suavizado inicial del campo\nde rotaciones"
optimizeRotationIterations = "Iteraciones para la optimización\nde la rotación"
steepOverhangCompensation = "Compensación de voladizo empinado"
calculateDeformationIterations = "Iteraciones para el calculo de la\ndesformación"
applyParameters = "Aplicar"
viewRotatedTriangles = "Ver triangulos rotados"
viewBottomMesh = "Ver voladizo"

homeAll = "Añadir recalibración al gcode (G28)"
heatUpExtruder = "Añadir temperatura al gcode\n(M104 y M109)"
